// Code generated by Kitex v0.4.2. DO NOT EDIT.
package operations

import (
	api "ClyMQ/kitex_gen/api"
	server "github.com/cloudwego/kitex/server"
)

// NewServer 创建一个新的 RPC 服务器
func NewServer(handler api.Operations, opts ...server.Option) server.Server {
	var options []server.Option // 创建一个空的服务器选项切片

	options = append(options, opts...)//将服务选项加入其中

	svr := server.NewServer(options...)//创建一个rpc的server
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {//向rpc中注册提供实际的服务逻辑
		panic(err)
	}
	return svr
}
